### ISSUE TITLE
Skater gets super shaky while everything else remains smooth. 

### ISSUE THREAD

**Issue by Straightforthefood** [DanielKIWI/SkaterXL-Modding#1]
So whenever i edit a clip, doesn't matter which mode ( freemode, tripod, ect ) the skater gets super shaky. It's just the skater though, everything else is smooth. Scenery, camera follow movement. 
I've heard other people having the same issue but i didn't see a bug report yet. 
I shouldn't be my pc, specs are way more than needed. 
Whatever causes it, i haven't found a fix yet. Thank you.

**Comment by DanielKIWI** [comment]
Thanks for the report man.
This Issue should be fixed in the latest Mod Release, so I will close this.
Let me know if you still have this Problem with the newest version.
